"""ゲームルール定数。"""

# デッキ構成
DECK_SIZE = 10  # MS 5 枚 + PL 5 枚
MS_SLOTS = 5
PL_SLOTS = 5

# カードタイプ
TYPE_MS = "MS"
TYPE_PL = "PL"
TYPE_CMD = "CMD"

# 色
COLOR_RED = "赤"
COLOR_BLUE = "青"
COLOR_GREEN = "緑"
VALID_COLORS = {COLOR_RED, COLOR_BLUE, COLOR_GREEN}
COLOR_ORDER = [COLOR_RED, COLOR_BLUE, COLOR_GREEN]

# ユニットカテゴリ（アーセナルベースと同じ殲滅/制圧/防衛を想定）
CATEGORY_SENMETSU = "殲滅"
CATEGORY_SEIATSU = "制圧"
CATEGORY_BOUEI = "防衛"
VALID_CATEGORIES = {CATEGORY_SENMETSU, CATEGORY_SEIATSU, CATEGORY_BOUEI}
